use_frameworks!

abstract_target 'Pod' do

 pod 'CDBiCloudKit', :path => '../'
 pod 'CDBKit', :path => '/Users/bucha/busyness/,github/CDBKit/'

    target 'CDBiCloudKit_Example' do
        target 'CDBiCloudKit_Tests' do
            inherit! :search_paths
        end
    end
    target 'CDBiCloudKit-Mac' do
    end
end

